### ISSUE TITLE
Feature 1: Register User Account

### ISSUE THREAD

**Issue by ghost** [UCCS-CS4300-5300/group6-spring2024#18]
User Story: As a prospective user, so that I can find the best new restaurants in my area I want to register to this foodie joint app.

Description: A user should be able to click on a button to register an account with the application. This should then allow the user to register with the required information and sign-in with the account in future sessions.

Lofi:

<img width="1040" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjluQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59344ee4845d4a45d56b39571290e139b04deb28/Lofi%20One.JPG" alt="Lofi One.JPG" />

Acceptance Criteria: 

Given that I have entered all of the correct information during the sign-up process,
When I click the register button,
Then the account will be created and be able to be used.

Given that I have not entered all of the required information during the sign-up process,
When I click the register button,
Then an error should prompt me to resubmit the information.

Given that I have not entered the correct type of information into an input field,
When I click the register button, 
Then an error should prompt me to resubmit the information.

**Comment by lflancher** [comment]
I've registered the user successfully but was unable to change the base user to accommodate an address connected for each of the users.
