### ISSUE TITLE
Feature 6: User Ability to Leave Review

### ISSUE THREAD

**Issue by ghost** [UCCS-CS4300-5300/group6-spring2024#2]
User Story: As a user who had went to a restaurant, so that other people may know what to expect, I want to leave a review on the app.

Description: When signed in as a user, when viewing an item's description, the user should be able to click the "add a review" button. This should then bring them to a new page that allows the user to leave a written review and a out of five stars rating as well.

Acceptance Criteria:

Given that I am signed into the application,
When I input all required information and click submit,
Then the review will successfully be added to the item.

Given that I am not signed into the application,
When I try to click the button to review the food item,
The the app will prompt me to sign in before allowing me to continue.

Given that I am signed into the application,
When I do not input all required information for the review and click submit,
Then the application will prompt me to reinput the information.

Given that I have entered a new review,
When I go back to the items menu,
Then the rating should reflect a new average between the added rating and existing ones.

**Comment by kobe-goodermont** [comment]
Finished
